"""Add investment name to price update logs

Revision ID: 033f79f94fc2
Revises: 3387bbf2f364
Create Date: 2026-05-14 18:30:57.445287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033f79f94fc2'
down_revision = '3387bbf2f364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_logs', schema=None) as batch_op:
        batch_op.drop_column('investment_name')

    # ### end Alembic commands ###
