"""Improve price update logs

Revision ID: 3387bbf2f364
Revises: 7fc155e8d2b7
Create Date: 2026-05-14 17:38:38.394400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3387bbf2f364'
down_revision = '7fc155e8d2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('users_uniq_id', 'users', ['uploaded_by'], ['id'])
        batch_op.create_foreign_key('investment_unique_id', 'investments', ['investment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')
        batch_op.drop_column('investment_id')

    # ### end Alembic commands ###
